//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 03:28:44 PM EEST 
//


package ro.digidata.esop.jobs.steps.model.extkey;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchema;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://esop.insse.ro/service/template/extendedKey}attribute" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attribute"
})
@XmlRootElement(name = "ext_key")
public class ExtKey {

    protected List<AttributeExtKeyType> attribute;

    /**
     * Gets the value of the attribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttributeExtKeyType }
     * 
     * 
     */
    public List<AttributeExtKeyType> getAttribute() {
        if (attribute == null) {
            attribute = new ArrayList<AttributeExtKeyType>();
        }
        return this.attribute;
    }

    public boolean hasAttributeWithValue( String name, String value ) {
        if ( attribute != null ) {
            for ( AttributeExtKeyType attr : attribute ) {
                if ( attr.getName( ).equals( name ) && attr.getValue( ).equals( value )) {
                    return true;
                }
            }
        }
        
        return false;
    }
    
    public void addAttribute( String name, String value ) {
        AttributeExtKeyType a = new AttributeExtKeyType( );
        a.setName( name );
        a.setValue( value );
        getAttribute().add( a );
    }

}
