//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 03:28:44 PM EEST 
//


package ro.digidata.esop.jobs.steps.model.extkey;

import javax.xml.XMLConstants;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ro.digidata.esop.model.extendedkey package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Attribute_QNAME = new QName("http://esop.insse.ro/service/template/extendedKey", "attribute", "");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ro.digidata.esop.model.extendedkey
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExtKey }
     * 
     */
    public ExtKey createExtKey() {
        return new ExtKey();
    }

    /**
     * Create an instance of {@link AttributeExtKeyType }
     * 
     */
    public AttributeExtKeyType createAttributeExtKeyType() {
        return new AttributeExtKeyType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeExtKeyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://esop.insse.ro/service/template/extendedKey", name = "attribute")
    public JAXBElement<AttributeExtKeyType> createAttribute(AttributeExtKeyType value) {
        return new JAXBElement<AttributeExtKeyType>(_Attribute_QNAME, AttributeExtKeyType.class, null, value);
    }

}
