//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 03:28:44 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://esop.insse.ro/service/template/extendedKey", xmlns = {
    @XmlNs(prefix = "", namespaceURI = "http://esop.insse.ro/service/template/extendedKey")
}, elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ro.digidata.esop.jobs.steps.model.extkey;

import javax.xml.bind.annotation.XmlNs;

