/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ro.digidata.esop.input;

import java.util.Scanner;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import ro.digidata.esop.input.commands.CommandLine;
import ro.digidata.esop.input.commands.UserCommand;
import ro.digidata.esop.input.commands.UserCommandFactory;
import ro.digidata.esop.input.exceptions.InvalidCommandException;
import ro.digidata.esop.input.exceptions.QuitException;

@Component
public class ShellRunner {

    @Autowired
    private UserCommandFactory factory;
    
    private String handleInput() {
        //promp the user
        promptUser();

        //read the input
        Scanner sc = new Scanner(System.in);
        String input = sc.nextLine();

        return input;
    }

    private void promptUser() {
        System.out.print("> ");
    }

    public void handleAllInputs( ) {
        try {
            //continue with the standard input; it will exit via a QuitException generated by a QuitCommand
            while (true) {
                try {
                String commandLineString = handleInput( );
		
		CommandLine commandLine = new CommandLine( commandLineString );
		
		//get the command to execute
		UserCommand command = factory.getCommand( commandLine.getCommand( ) );
		
		//execute the command
		command.execute( commandLine.getParameters( ) );
                
                } catch (InvalidCommandException  ex ) {
                    //invalid command; print message and retry
                    System.out.println(String.format("%s. Introduceti din nou!", ex.getMessage()));
                }
            }
        } catch (QuitException  exQE) {
            //gracefully ended it; nothing to do hear
        }
    }
}
