/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ro.digidata.esop.input;

import java.util.Scanner;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import ro.digidata.esop.input.commands.UserCommandFactory;

@Component
public class ShellRunner {

    @Autowired
    private UserCommandFactory factory;
    
    private String handleInput() {
        //promp the user
        promptUser();

        //read the input
        Scanner sc = new Scanner(System.in);
        String input = sc.nextLine();

        return input;
    }

    private void promptUser() {
        System.out.print("> ");
    }

    public void handleAllInputs( ) {
        try {
            //continue with the standard input; it will exit via a QuitException generated by a QuitCommand
            while (true) {
                try {
                String command = handleInput( );
                
                } catch (Exception  ex ) {
                    //invalid command; retry again
                    System.out.println("Introduceti din nou comanda:");
                }
            }
        } catch (Exception  exQE) {
            //gracefully ended it; nothing to do hear
        }
    }
}
