//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 03:33:26 PM EEST 
//


package ro.digidata.esop.jobs.steps.model.authorization;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ro.digidata.esop.model.authorization package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Survey_QNAME = new QName("http://esop.insse.ro/service/template/authorization", "survey");
    private final static QName _Unit_QNAME = new QName("http://esop.insse.ro/service/template/authorization", "unit");
    private final static QName _Questionnaire_QNAME = new QName("http://esop.insse.ro/service/template/authorization", "questionnaire");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ro.digidata.esop.model.authorization
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UnitType }
     * 
     */
    public UnitType createUnitType() {
        return new UnitType();
    }

    /**
     * Create an instance of {@link QuestionnaireType }
     * 
     */
    public QuestionnaireType createQuestionnaireType() {
        return new QuestionnaireType();
    }

    /**
     * Create an instance of {@link SurveyType }
     * 
     */
    public SurveyType createSurveyType() {
        return new SurveyType();
    }

    /**
     * Create an instance of {@link Authorization }
     * 
     */
    public Authorization createAuthorization() {
        return new Authorization();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SurveyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://esop.insse.ro/service/template/authorization", name = "survey")
    public JAXBElement<SurveyType> createSurvey(SurveyType value) {
        return new JAXBElement<SurveyType>(_Survey_QNAME, SurveyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnitType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://esop.insse.ro/service/template/authorization", name = "unit")
    public JAXBElement<UnitType> createUnit(UnitType value) {
        return new JAXBElement<UnitType>(_Unit_QNAME, UnitType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QuestionnaireType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://esop.insse.ro/service/template/authorization", name = "questionnaire")
    public JAXBElement<QuestionnaireType> createQuestionnaire(QuestionnaireType value) {
        return new JAXBElement<QuestionnaireType>(_Questionnaire_QNAME, QuestionnaireType.class, null, value);
    }

}
